apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-2
spec:
  parallelism: 2
  template:
    metadata:
      name: job-wq-2
    spec:
      containers:
      - name: job-wq
        image: aws-account-no.dkr.ecr.us-east-1.amazonaws.com/job-wq-2:latest
      restartPolicy: OnFailure
